In [3]:
import numpy as np
#numpy as np means nickname
import pandas as pd
from matplotlib import pyplot as plt

In [6]:
#Creating a Numpy Array
list =[1,2,3,4]

arr=np.array(list)
#print(arr) equals under code
print(np.array(list)) 

[1 2 3 4]


In [8]:
#.dtype attribute
print(arr.dtype)
#위의 코드에서 list에 int 형을 사용해서 4바이트 즉 32비트이다
#<U 로시작한다면 list에 한가지 자료형뿐아니라 여러가지 자료형을 사용함

int32


In [13]:
"""
Size of ndarray and list objects
"""
from sys import getsizeof

list=[1]
print(getsizeof(list)) #아이템 0:56  1개:64

arr=np.array(list)
print(getsizeof(arr)) #원소0: 104  1개 108
#numpy array는 값만 추가하기때문에 4바이트
#리스트는 값과 객체에대한 정보를 추가하므로 8바이트
#원소의 갯수가 많아질수록 numpy array로 만드는 게 유리하다

64
108


In [16]:
"""
Operations with Numpy Arrays
"""
prices=[30,25,40,20,20,35,50,35]

#with a list
new_price=[price-5 for price in prices]
print(new_price)

#with a ndarray
prices_arr=np.array(prices)
prices_arr-=5
print(prices_arr)

#ndarray로 처리할땐 사용이 편하다

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [35]:
"""
ExerCise:Test Scores
"""

test_1=np.array([92,94,88,91,87])
test_2=np.array([79,100,86,93,91])
test_3=np.array([87,85,72,90,92])

test_3_fixed=test_3+2
print(test_3_fixed)

total_grade = test_1+test_2+test_3
print(total_grade)
final_grade=total_grade/3
print(final_grade)

jeremy_test_2=test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1=np.array([test_1[1],test_1[2]])
print(manual_adwoa_test_1)

#2차원 배열로 만들기
student_scores=np.array([test_1,test_2,test_3])
print(student_scores)

#:은 전체선텍
print(student_scores[2,0])
print(student_scores[:,4])


[89 87 74 92 94]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [40]:
"""
Logical Operations with Arrays
"""

a=np.array([10,2,2,4,5,3,9,8,9,7])
mask=a>5
print(mask)

#selecting using logical operations
#조건에 맞는 원소만 뽑아서 부분집합 만들기
selected=a[a>5]
print(selected)

#combined logical operations
selected=a[(a>6)|(a<4)]
print(selected)

selected=a[(a>4)&(a<8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5 7]


In [45]:
"""
Exercise:Goldilocks Porridge Festival
"""

porridge=np.array([79,65,50,63,56,90,85,98,79,51])
cold=porridge[porridge<60]
print(cold)

hot=porridge[porridge>80]
print(hot)

just_right=porridge[(porridge>60)&(porridge<80)]
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]
