In [1]:
import numpy as np

In [26]:
"""
computing reciprocals in loops
"""

def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

np.random.seed(0)
values=np.random.randint(1,10,size=5)
print(values)
compute_reciprocals(values)

[6 1 4 4 8]


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [27]:
"""
Comparison:loop vs ufuncs(vectorized)
"""
#loop
big_array=np.random.randint(1,100,size=1000000)

%timeit compute_reciprocals(big_array)

2.31 s ± 10.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [30]:
#vectorized 가 훨씬 빠른것을 확인가능하다
%timeit 1/big_array

2.93 ms ± 35.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
"""
UFunction
"""

np.random.seed(1)

arr1=np.random.randint(10,size=5)
arr2=np.random.randint(10,size=5)

print(arr1,arr2)
arr1=arr2-2
print(arr1,arr2)

arr3=arr1+arr2
print(arr3)

arr4=np.random.randint(10,size=(3,5))
print(arr4)
arr5=arr4**2
print(arr5)
#파이썬의 루프보다 수월하다

[5 8 9 5 0] [0 1 7 6 9]
[-2 -1  5  4  7] [0 1 7 6 9]
[-2  0 12 10 16]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [35]:
"""
Array Arithmetic
"""

x=np.arange(4)
print("x    =",x)
print("x+5  =",x+5)
print("x-5  =",x-5)
print("x*2  =",x*2)
print("x/2  =",x/2)
print("x**2 =",x**2)

print("x+5  =",np.add(x,5))
print("x-5  =",np.subtract(x,5))
print("x*2  =",np.multiply(x,2))
print("x/2  =",np.divide(x,2))
print("x**2 =",np.power(x,2))


x    = [0 1 2 3]
x+5  = [5 6 7 8]
x-5  = [-5 -4 -3 -2]
x*2  = [0 2 4 6]
x/2  = [0.  0.5 1.  1.5]
x**2 = [0 1 4 9]
x+5  = [5 6 7 8]
x-5  = [-5 -4 -3 -2]
x*2  = [0 2 4 6]
x/2  = [0.  0.5 1.  1.5]
x**2 = [0 1 4 9]


In [40]:
"""
UFunc:abs
"""

x=np.array([-2,-1,0,1,2])
print(np.abs(x))

x=np.array([3-4j,4-3j,2+0j,0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [46]:
"""
UFunc:Aggregation
"""

theta=np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

x=np.linspace(0,100,11)
print(x)


[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [48]:
"""
Aggragation
"""
x=np.arange(1,5)
print(x)
aggr=np.add.reduce(x)
aggr1=np.multiply.reduce(x)
print(aggr,aggr1)

[1 2 3 4]
10 24


In [51]:
"""
accumulation
"""
x=np.arange(1,5)
accum=np.add.accumulate(x)
print(accum)

accum=np.multiply.accumulate(x)
print(accum)

[ 1  3  6 10]
[ 1  2  6 24]


In [54]:
"""
Ufunc sum vs python sum
""" 
np.random.seed(3)
arr=np.random.rand(100000)
print(arr)
print("sum= ",np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.12599742 0.94189543 0.89025983]
sum=  50103.284993937086


In [59]:
%timeit sum(arr)


9.28 ms ± 227 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [60]:
%timeit np.sum(arr)

34.8 µs ± 130 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [64]:
"""
other aggr
"""
print("max=",np.max(arr))
print("min=",np.min(arr))
print("mean=",np.mean(arr))
print("median=",np.median(arr))
print("percentile=",np.percentile(arr,90))

print(np.any(arr>1))
print(np.all(arr>0))


max= 0.9999992160832805
min= 1.4735641223229123e-05
mean= 0.5010328499393709
median= 0.5003519408181236
percentile= 0.9017140534612551
False
True


In [66]:
"""
Multi dimendional aggregates
"""

np.random.seed(5)
arr=np.random.randint(10,size=(3,4))
print(arr)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
